

openapi: 3.0.0
info:
  title: Sherlock Timeline Module API
  description: Sherlock reports module interface
  version: 0.1.9
servers:
  - url: http://localhost:3034/
    description: development server
  - url: http://localhost:3034/
    description: Testing server

components:
  parameters:
    offsetParam:
      name: offset
      in: query
      description: offset of the list
      schema:
        type: integer
        default: 0
      required: false
    limitParam:
      name: limit
      in: query
      description: amount of items to be returned
      required: false
      schema:
        type: integer
        default: 10
  schemas:
    TimelineResponseData:
      type: object
      properties:
        title: 
          type: string
          description: timeline title
        projectId:
          type: number
          description: project id
        log:
          type: object
          description: log data
        lines:
          type: array
          description: timelines line
        updatedAt:
          type: string
          description: last update date
        createdAt:
          type: string
          description: creation date
      example:
        title: "timeline1"
        projectId: 1
        lines: []
        log: {}
        createdAt: "2022-07-30T19:27:13.357Z"
        updatedAt: "2022-07-30T19:27:13.357Z"
    TimelineRequest:
      type: object
      properties:
        title: 
          type: string
          description: timeline title
        lines:
          type: array
          description: lines mongo ids
        log:
          type: string
          description: log mongo id
      example:
        title: timeline1
        log: 62e557770cda67a071353283 
        lines: ["62e557770cda67a071353287", "62e557770cda67a071353288"]
    LogHeader:
      type: object
      properties:
        _id:
          type: string
          description: Log ID
        title:
          type: string
          description: Log title
        description:
          type: string
          description: Log description
        projectId:
          type: string
          description: ID of the project
        status:
          type: string
          description: status of the log
          enum: 
          - processing
          - processed
      example:
        _id: "62d776f235ca54db99e4765e"
        title: pepe.txt
        description: "This is a log file"
        projectId: 123456789
        status: "processing"
tags:
  - name: Timeline CRUD
    description: timeline creation, modification and remove

paths:
  /project/:projectId/timeline:
    post:
      summary: Creates a timeline
      tags: [Timeline CRUD]
      description: Creates a timeline
      parameters:
      - name: projectId
        in: path
        description: "Project ID"
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimelineRequest'
      responses:
        '200':
          description: Timeline data response
          content:
            application/json:
              schema: 
                type: object
                items:
                  $ref: '#/components/schemas/TimelineResponseData'
