services:
  mysql:
    profiles: [ "all", "mysql" ]
    build: ./mysql
    ports:
      - "3306:3306"

  mongo:
    profiles: [ "all", "mongo" ]
    build: ./mongo
    ports:
      - "27017:27017"

  usuarios:
    profiles: [ "all", "usuarios" ]
    build: ./usuarios
    ports:
      - "3030:3030"
    depends_on:
      - mysql

  ips:
    profiles: [ "all", "ips" ]
    build: ./ips
    ports:
      - "3031:3031"
    depends_on:
      - mongo

  correlacion:
    profiles: [ "all", "correlacion" ]
    build: ./correlacion
    ports:
      - "3032:3032"
    depends_on:
      - mongo

  busqueda:
    profiles: [ "all", "busqueda" ]
    build: ./busqueda
    ports:
      - "3033:3033"
    depends_on:
      - mongo

  timeline:
    profiles: [ "all", "timeline" ]
    build: ./timeline
    ports:
      - "3034:3034"
    depends_on:
      - mongo
  fake-gateway:
    profiles: [ "all", "gateway" ]
    build: ./fake-gateway
    ports:
      - "3035:3035"
    depends_on:
      - mongo
      - usuarios
      - ips
      - correlacion
      - busqueda
      - timeline
