services:
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    networks: 
      - users
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
    networks: 
      - business
  usuarios:
    build: ./usuarios
    ports:
      - "3030:3030"
    depends_on:
      - mysql
    networks: 
      - users
  ips:
    build: ./ips
    ports:
      - "3031:3031"
    depends_on:
      - mongo
    networks: 
      - business
  correlacion:
    build: ./correlacion
    ports:
      - "3032:3032"
    depends_on:
      - mongo
    networks: 
      - business
  busqueda:
    build: ./busqueda
    ports:
      - "3033:3033"
    depends_on:
      - mongo
    networks: 
      - business
  timeline:
    build: ./timeline
    ports:
      - "3034:3034"
    depends_on:
      - mongo
    networks: 
      - business
networks:
  users:
      name: "users-network"
      driver: bridge
  business:
      name: "business-network"
      driver: bridge