

openapi: 3.0.0
info:
  title: Sherlock User Module API
  description: Sherlock security user module interface
  version: 0.1.9
servers:
  - url: http://localhost:3032/
    description: development server
  - url: http://localhost:3032/
    description: Testing server

components:
  schemas:
    LogRequest:
      type: object
      properties:
        title: 
          type: string
          description: Log title
        description:
          type: string
          description: Log description
    LogHeader:
      type: object
      properties:
        _id:
          type: string
          description: Log ID
        title:
          type: string
          description: Log title
        description:
          type: string
          description: Log description
        projectId:
          type: string
          description: ID of the project
      example:
        _id: 62d776f235ca54db99e4765e
        title: pepe.txt
        description: "This is a log file"
        projectId: 123456789
paths:
  /project/:projectId/correlate/log:
    post:
      summary: Creates an array of logs
      description: Creates an array of logs
      requestBody:
        content: 
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  description: Logs to be correlated
                  items:
                    type: string
                metadata:
                  description: Metadata to be correlated, is an array of LogRequest as STRING
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/LogHeader'
